#### 1) Dataset: product-info.csv. 
#### Problem: Write a Python program to calculate the total sales, average sales price, and the standard deviation of sales prices. Additionally, identify the product with the highest and lowest average sales price. 

In [9]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(os.getcwd())

C:\Users\Snehal\Desktop\Data Science Training 2024


In [11]:
df= pd.read_csv("datasets//product-info.csv")
df

Product ID    Product Name  Price  Quantity Sold  Sales Date
0         101      Blue Jeans  59.99             20  2023-12-15
1         102       Red Shirt  24.99             35  2023-12-20
2         103     Black Shoes  79.99             15  2023-12-25
3         104    Green Jacket  99.99             10  2023-12-30
4         105  White Sneakers  64.99             25  2024-01-05
5         106      Gray Pants  49.99             40  2024-01-10
6         107    Yellow Dress  39.99             30  2024-01-15
7         108      Brown Belt  19.99             50  2024-01-20
8         109      Purple Hat  14.99             60  2024-01-25
9         110    Orange Socks   9.99             75  2024-01-30

In [ ]:
# Gross Sales = Sum of all sales (Total units sold x Sales price per unit).
# Sales Revenue = Units Sold x Sales Price

In [25]:
total_sales = df['Price'] * df['Quantity Sold']
total_sales

0    1199.80
1     874.65
2    1199.85
3     999.90
4    1624.75
5    1999.60
6    1199.70
7     999.50
8     899.40
9     749.25
dtype: float64

In [23]:
print("Total Sales: ", total_sales.sum())
print("Average Sales Price: ", total_sales.mean())
print("Standard Deviation of Sales Price: ", total_sales.std())

Total Sales:  11746.4
Average Sales Price:  1174.6399999999999
Standard Deviation of Sales Price:  379.0295186393799


In [28]:
#average selling price of a product = take the total revenue earned from the product/divide it by the number of products sold.
avg_selling_price_product = total_sales/total_sales.count()
avg_selling_price_product

0    119.980
1     87.465
2    119.985
3     99.990
4    162.475
5    199.960
6    119.970
7     99.950
8     89.940
9     74.925
dtype: float64

In [43]:
print("Product with max avg_selling_price: \n", df.loc[avg_selling_price_product.idxmax()])

product with max avg_selling_price: 
 Product ID              106
Product Name     Gray Pants
Price                 49.99
Quantity Sold            40
Sales Date       2024-01-10
Name: 5, dtype: object


In [44]:
print("Product with min avg_selling_price: \n", df.loc[avg_selling_price_product.idxmin()])

Product with min avg_selling_price: 
 Product ID                110
Product Name     Orange Socks
Price                    9.99
Quantity Sold              75
Sales Date         2024-01-30
Name: 9, dtype: object


#### 2) Dataset: A CSV file customer-satisfaction.csv 
#### Problem: Create a Python program to calculate the mean, median, and mode of the satisfaction ratings. Analyze the data by grouping it by age groups and gender to identify any trends. 

In [46]:
df= pd.read_csv("datasets//customer-satisfaction.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'datasets//customer-satisfaction.csv'

#### 3) Dataset: A CSV file house-info.csv 
#### Problem: Develop a Python program to calculate the first, second (median), and third quartiles of house prices. Also, compute the interquartile range (IQR) and identify any outliers in the dataset

In [64]:
df= pd.read_csv("datasets//house-info.csv")
df

House ID  Location  Number of Bedrooms  Square Footage     Price
0          1  Suburban                   3            1800  $350,000
1          2     Urban                   2            1200  $280,000
2          3     Rural                   4            2500  $400,000
3          4  Suburban                   3            1600  $320,000
4          5     Urban                   1             800  $200,000
5          6     Rural                   5            3000  $450,000
6          7  Suburban                   2            1400  $290,000
7          8     Urban                   3            1600  $310,000
8          9     Rural                   4            2800  $420,000
9         10  Suburban                   3            1700  $330,000
10        11     Urban                   2            1100  $270,000
11        12     Rural                   5            3200  $470,000
12        13  Suburban                   3            1500  $900,000
13        14     Urban                   1             900  $210,000
14        15     Rural                   4            9600  $410,000
15        16  Suburban                   3            1800  $340,000
16        17     Urban                   2            1200  $280,000
17        18     Rural                   5            2500  $400,000
18        19  Suburban                   3            1600  $320,000
19        20     Urban                   1             800  $200,000
20        21     Rural                   4            3000  $950,000
21        22  Suburban                   2            1400  $290,000
22        23     Urban                   3            1600  $310,000
23        24     Rural                   4            2800  $420,000
24        25  Suburban                   3            1700  $330,000

In [65]:
df['Price'] = df['Price'].str.replace('$', '') # Remove '$'
df['Price'] = df['Price'].str.replace(',', '') # Remove ','
df['Price'] = df['Price'].astype(int) # Convert to int
df['Price']

C:\Users\Snehal\AppData\Local\Temp/ipykernel_2068/3310978764.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Price'] = df['Price'].str.replace('$', '') # Remove '$'


0     350000
1     280000
2     400000
3     320000
4     200000
5     450000
6     290000
7     310000
8     420000
9     330000
10    270000
11    470000
12    900000
13    210000
14    410000
15    340000
16    280000
17    400000
18    320000
19    200000
20    950000
21    290000
22    310000
23    420000
24    330000
Name: Price, dtype: int32

In [66]:
prices = np.array(df['Price'])
prices

array([350000, 280000, 400000, 320000, 200000, 450000, 290000, 310000,
       420000, 330000, 270000, 470000, 900000, 210000, 410000, 340000,
       280000, 400000, 320000, 200000, 950000, 290000, 310000, 420000,
       330000])

In [69]:
print("First Quartile: ", np.percentile(prices,25))
print("Second Quartile: ", np.percentile(prices,50))
print("First Quartile: ",np.percentile(prices,75))

First Quartile:  290000.0
Second Quartile:  330000.0
First Quartile:  410000.0


In [70]:
Q1 = np.percentile(prices,25)
Q3 = np.percentile(prices,75)

IQR = Q3 - Q1
print("Inter Quartile Range: ", IQR)

Inter Quartile Range:  120000.0


In [71]:
upper_fence = Q3 + 1.5 * IQR
lower_fence = Q1 - 1.5 * IQR

In [73]:
(prices > upper_fence) 

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False])

In [74]:
(prices < lower_fence)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [80]:
outliers = prices[prices > upper_fence]
outliers

array([900000, 950000])

In [87]:
prices[prices < lower_fence]

array([], dtype=int32)

In [88]:
np.where(prices == outliers[0])[0][0] # To get outlier index in an array

12

In [89]:
for x in outliers:
    print(df.loc[np.where(prices == x)[0][0]])
    print("\n")

House ID                    13
Location              Suburban
Number of Bedrooms           3
Square Footage            1500
Price                   900000
Name: 12, dtype: object


House ID                  21
Location               Rural
Number of Bedrooms         4
Square Footage          3000
Price                 950000
Name: 20, dtype: object




#### 4) Dataset: A CSV file visitor-info.csv 
#### Problem: Create a Python program to analyze the average, minimum, and maximum number of visitors per day. Investigate the relationship between bounce rate and conversion rate using correlation analysis

In [91]:
df= pd.read_csv("datasets//visitor-info.csv")
df

Date  Number of Visitors  Average Session Duration (seconds)  \
0   2023-12-01                5000                                 120   
1   2023-12-02                4500                                 130   
2   2023-12-03                5500                                 115   
3   2023-12-04                6000                                 125   
4   2023-12-05                4800                                 135   
5   2023-12-06                5200                                 120   
6   2023-12-07                4700                                 130   
7   2023-12-08                5600                                 115   
8   2023-12-09                6200                                 125   
9   2023-12-10                4900                                 135   
10  2023-12-11                5100                                 120   
11  2023-12-12                4600                                 130   
12  2023-12-13                5400                                 115   
13  2023-12-14                6100                                 125   
14  2023-12-15                5000                                 135   
15  2023-12-16                4500                                 120   
16  2023-12-17                5500                                 130   
17  2023-12-18                6000                                 115   
18  2023-12-19                4800                                 125   
19  2023-12-20                5200                                 135   
20  2023-12-21                4700                                 120   
21  2023-12-22                5600                                 130   
22  2023-12-23                6200                                 115   
23  2023-12-24                4900                                 125   
24  2023-12-25                5100                                 135   
25  2023-12-26                4600                                 120   
26  2023-12-27                5400                                 130   
27  2023-12-28                6100                                 115   
28  2023-12-29                5000                                 125   

    Bounce Rate (%)  Conversion Rate (%)  
0                25                  2.0  
1                22                  3.0  
2                28                  1.5  
3                20                  2.5  
4                23                  2.0  
5                25                  2.2  
6                22                  2.8  
7                28                  1.7  
8                20                  2.7  
9                23                  2.1  
10               25                  2.3  
11               22                  2.9  
12               28                  1.8  
13               20                  2.6  
14               23                  2.2  
15               25                  2.4  
16               22                  2.7  
17               28                  1.6  
18               20                  2.5  
19               23                  2.1  
20               25                  2.3  
21               22                  2.9  
22               28                  1.8  
23               20                  2.6  
24               23                  2.2  
25               25                  2.4  
26               22                  2.7  
27               28                  1.6  
28               20                  2.5

In [112]:
avg_no_visitor_per_day = df['Number of Visitors'].sum() / df.count()
min_no_visitor_per_day = df['Number of Visitors'].min()
max_no_visitor_per_day = df['Number of Visitors'].max()

In [113]:
print("Avg no. of Visitors per day: ", avg_no_visitor_per_day['Number of Visitors'])
print("Min no. of Visitors per day: ", min_no_visitor_per_day)
print("Max no. of Visitors per day: ", max_no_visitor_per_day)

Avg no. of Visitors per day:  5248.275862068966
Min no. of Visitors per day:  4500
Max no. of Visitors per day:  6200


In [122]:
bounce_arr = np.array(df['Bounce Rate (%)'])
conversion_arr = np.array(df['Conversion Rate (%)'])

np.corrcoef(bounce_arr,conversion_arr)

array([[ 1.        , -0.81660505],
       [-0.81660505,  1.        ]])

In [123]:
print("Bounce Rate and Conversion Rate have a negative co-relation of : ", np.corrcoef(bounce_arr,conversion_arr)[0][1])

Bounce Rate and Conversion Rate have a negative co-relation of :  -0.8166050475362996


#### 5) Dataset: A CSV file purchase-info.csv 
#### Problem: Develop a Python program to calculate the average purchase amount for each category. Also, find the most frequent purchase category and the customer who made the most purchases.

In [125]:
df= pd.read_csv("datasets//purchase-info.csv")
df

Customer ID  Purchase Amount Purchase Date     Category
0          1001               50    2023-12-01  Electronics
1          1002               25    2023-12-02     Clothing
2          1003               75    2023-12-03   Home Goods
3          1004               40    2023-12-04  Electronics
4          1005               30    2023-12-05     Clothing
5          1006               60    2023-12-06   Home Goods
6          1007               20    2023-12-07  Electronics
7          1008               55    2023-12-08     Clothing
8          1009               80    2023-12-09   Home Goods
9          1010               35    2023-12-10  Electronics
10         1011               28    2023-12-11     Clothing
11         1012               65    2023-12-12   Home Goods
12         1013               18    2023-12-13  Electronics
13         1014               52    2023-12-14     Clothing
14         1015               78    2023-12-15   Home Goods
15         1016               32    2023-12-16  Electronics
16         1017               26    2023-12-17     Clothing
17         1018               63    2023-12-18   Home Goods
18         1019               16    2023-12-19  Electronics
19         1020               54    2023-12-20     Clothing
20         1021               76    2023-12-21   Home Goods
21         1022               34    2023-12-22  Electronics
22         1023               27    2023-12-23     Clothing
23         1024               62    2023-12-24   Home Goods
24         1025               17    2023-12-25  Electronics
25         1026               53    2023-12-26     Clothing
26         1027               75    2023-12-27   Home Goods
27         1028               35    2023-12-28  Electronics
28         1029               28    2023-12-29     Clothing
29         1030               65    2023-12-30   Home Goods

In [148]:
avg_purchase_amount_category = df.groupby('Category')['Purchase Amount'].sum()

print("The average purchase amount for each category:\n", avg_purchase_amount_category)

The average purchase amount for each category:
 Category
Clothing       378
Electronics    297
Home Goods     699
Name: Purchase Amount, dtype: int64


In [139]:
print("Most Frequent purchase category : ")
df['Category'].value_counts()

Most Frequent purchase category : 


Electronics    10
Clothing       10
Home Goods     10
Name: Category, dtype: int64

In [136]:
print("Customer who made most purchases : ")
df['Customer ID'].value_counts()

Customer who made most purchases : 


1001    1
1002    1
1029    1
1028    1
1027    1
1026    1
1025    1
1024    1
1023    1
1022    1
1021    1
1020    1
1019    1
1018    1
1017    1
1016    1
1015    1
1014    1
1013    1
1012    1
1011    1
1010    1
1009    1
1008    1
1007    1
1006    1
1005    1
1004    1
1003    1
1030    1
Name: Customer ID, dtype: int64